version: '3.9'
volumes:
  db:
services:
  db:
    container_name: rideshare-db
    image: "public.ecr.aws/docker/library/postgres:16"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  rideshare:
    build:
      context: .
      target: build
    container_name: rideshare
    ports:
      - "3000:3000" # puma rails server
    volumes:
      - .:/rails
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: 1
      PG_HOST: rideshare-db
      PG_PORT: 5432
      PG_USERNAME: postgres
      PG_PASSWORD: password
